services:
  db:
    container_name: database
    image: mariadb:10.7.8-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-wordpress}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-wordpress}
    ports:
      - "3306:3306"
    expose:
      - 3306
      - 33060
    networks:
      - lan

  pma:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - '127.0.0.1:3307:80'
    networks:
      - lan

  wp:
    container_name: wordpress
    build:
      context: ./wordpress1
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - mailpit
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE:-wordpress}
      - WORDPRESS_DB_USER=${MYSQL_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD:-wordpress}
      - WORDPRESS_DEBUG=${DEBUG:-false}
      - WORDPRESS_SMTP_HOST=${WORDPRESS_SMTP_HOST:-mailpit}
      - WORDPRESS_SMTP_PORT=${WORDPRESS_SMTP_PORT:-1025}
      - SMTP_HOSTNAME=${SMTP_HOSTNAME:-mailpit}
      - SMTP_PORT=${SMTP_PORT:-"1025"}
      - SMTP_USER=${SMTP_USER:-local@example.com}
      - SMTP_FROM=${SMTP_FROM:-local@example.com}
    volumes:
      - './wordpress1/src:/var/www/html'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - lan

  mailpit:
    container_name: mailpit
    image: 'axllent/mailpit:latest'
    restart: unless-stopped
    volumes:
      - ./mailpit_data:/data
    ports:
      - "127.0.0.1:8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      TZ: UTC # Setting the container's time zone to UTC
    networks:
      - lan

volumes:
  db_data:
  mailpit_data:

networks:
  lan:
    driver: bridge
